# Generated by Django 5.1.3 on 2025-02-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitt', '0002_rename_registro_registroactividad_objetivo_activado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, unique=True, verbose_name='Usuario'),
        ),
    ]
