# Generated by Django 5.1.3 on 2025-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitt', '0003_remove_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='activado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivos',
            field=models.ManyToManyField(through='fitt.ObjetivoUsuario', to='fitt.objetivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatar/', verbose_name='Foto de Perfil'),
        ),
    ]
