# Generated by Django 5.1.3 on 2025-02-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitt', '0004_remove_objetivo_activado_usuario_objetivos_and_more'),
    ]

    operations = [
    ]
