# Generated by Django 5.1.3 on 2025-02-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitt', '0006_remove_usuario_objetivos_marcados_and_more'),
    ]

    operations = [
    ]
