# Generated by Django 5.1.3 on 2025-02-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitt', '0007_auto_20250220_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivousuario',
            name='tiempo',
        ),
    ]
