# Generated by Django 5.1.3 on 2025-02-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitt', '0009_alter_registroactividad_fecha'),
    ]

    operations = [
    ]
